=== SlapOS/slapos/slapos/test/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Slapos Software Release instantiation descriptor",
  "additionalProperties": false,
  "properties": {
    "name": {
      "description": "A short human-friendly name for the sofware release",
      "type": "string"
    },
    "description": {
      "description": "A short description of the sofware release",
      "type": "string"
    },
    "serialisation": {
      "description": "How the parameters and results are serialised",
      "require": true,
      "enum": ["xml", "json-in-xml"],
      "type": "string"
    },
    "software-type": {
      "description": "Existing software types",
      "require": true,
      "patternProperties": {
        ".*": {
          "description": "Software type declaration",
          "additionalProperties": false,
          "properties": {
            "title": {
              "description": "A human-friendly title of the software type",
              "type": "string"
            },
            "description": {
              "description": "A human-friendly description of the software type",
              "type": "string"
            },
            "serialisation": {
              "description": "How the parameters and results are serialised, if different from global setting",
              "enum": ["xml", "json-in-xml"],
              "type": "string"
            },
            "request": {
              "require": true,
              "description": "URL, relative to Software Release base path, of a json schema for values expected by instance of current software type",
              "type": "string"
            },
            "response": {
              "require": true,
              "description": "URL, relative to Software Release base path, of a json schema for values published by instance of current software type",
              "type": "string"
            },
            "index": {
              "description": "Value to use instead of software type id to sort them (in order to display most relevant software types earlier in a list, for example)",
              "type": "number"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}

=== SlapOS/slapos/software/gitea/software.cfg.json
{
  "name": "Gitea",
  "description": "Gitea",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "Default",
      "description": "Gitea",
      "request": "instance-input-schema.json",
      "response": "instance-output-schema.json",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/re6stnet/software.cfg.json
{
  "name": "RE6STNET",
  "description": "Master instance of re6st (Resilient, Scalable, IPv6 Network application)",
  "serialisation": "xml",
  "software-type": {
    "default": {
      "title": "Default",
      "description": "Re6st registry",
      "request": "instance-re6stnet-input-schema.json",
      "response": "instance-re6stnet-output-schema.json",
      "index": 0
    },
    "default-slave": {
      "title": "Re6st Token",
      "description": "Re6st registry",
      "software-type": "default",
      "request": "instance-re6stnet-slave-input-schema.json",
      "response": "instance-re6stnet-output-schema.json",
      "shared": true,
      "index": 1
    }
  }
}

=== SlapOS/slapos/software/mail-server-relay/software.cfg.json
{
  "name": "Mail Server",
  "description": "Mail Server",
  "serialisation": "json-in-xml",
  "software-type": {
    "cluster": {
      "title": "Mail Server Cluster",
      "software-type": "cluster",
      "request": "instance-cluster-input-schema.json",
      "response": "instance-cluster-output-schema.json",
      "index": 0
    },
    "cluster-slave": {
      "title": "Mail Server Cluster Slave",
      "software-type": "cluster",
      "request": "instance-slave-input-schema.json",
      "response": "instance-slave-output-schema.json",
      "shared": true,
      "index": 1
    },
    "relay": {
      "title": "Mail Server Relay",
      "software-type": "relay",
      "request": "instance-relay-input-schema.json",
      "response": "instance-relay-output-schema.json",
      "index": 2
    },
    "omailgw": {
      "title": "oMailGw API/UI",
      "software-type": "omailgw",
      "request": "instance-omailgw-input-schema.json",
      "response": "instance-omailgw-output-schema.json",
      "index": 3
    }
  }
}

=== SlapOS/slapos/software/dovecot/software.cfg.json
{
  "name": "ERP5",
  "description": "ERP5, Open-Source ERP",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "Default",
      "software-type": "default",
      "request": "instance-dovecot-input-schema.json",
      "response": "instance-dovecot-output-schema.json",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/simpleran/software.cfg.json
{
  "name": "Amarisoft stack",
  "description": "4G and 5G amarisoft stack",
  "serialisation": "json-in-xml",
  "software-type": {
    "enb": {
      "title": "eNB/gNB",
      "software-type": "enb",
      "description": "eNodeB/gNodeB Configuration",
      "request": "instance-enb-input-schema.json",
      "response": "instance-enb-schema.json",
      "index": 1
    },
    "enb/*": {
      "title": "→  eNB/gNB | Radio Unit / Cell / Peer / Peer Cell",
      "description": "Configuration of a shared instance attached to eNB/gNB",
      "software-type": "enb",
      "shared": true,
      "request": "instance-enb-item-input-schema.json",
      "response": "instance-enb-item-schema.json",
      "index": 2
    },
    "core-network": {
      "title": "Core Network",
      "software-type": "core-network",
      "description": "Core Network Configuration",
      "request": "instance-core-network-input-schema.json",
      "response": "instance-core-network-schema.json",
      "index": 3
    },
    "core-network-slave": {
      "title": "→ Core Network | Sim Card",
      "description": "Core Network Sim Card Configuration",
      "software-type": "core-network",
      "request": "sim/input-schema.json",
      "response": "sim/schema.json",
      "shared": true,
      "index": 4
    },
    "ue": {
      "title": "UEsim",
      "description": "UEsim Configuration",
      "software-type": "ue",
      "request": "instance-ue-input-schema.json",
      "response": "instance-ue-schema.json",
      "index": 5
    },
    "ue/*": {
      "title": "→ UEsim | Radio Unit / UE / UE Cell",
      "description": "Configuration of a shared instance attached to UEsim",
      "software-type": "ue",
      "shared": true,
      "request": "instance-ue-item-input-schema.json",
      "response": "instance-ue-item-schema.json",
      "index": 6
    },
    "test": {
      "title": "Test",
      "description": "Test",
      "software-type": "test",
      "request": "test-input-schema.json",
      "response": "test-schema.json",
      "index": 7
    }
  }
}

=== SlapOS/slapos/software/simpleran/software-ors.cfg.json
{
  "name": "Simpleran",
  "description": "4G and 5G amarisoft stack for ORS",
  "serialisation": "json-in-xml",
  "software-type": {
    "enb-gnb": {
      "title": "eNB / gNB",
      "software-type": "enb-gnb",
      "description": "eNodeB / gNodeB Configuration",
      "request": "instance-ors-enb-gnb-input-schema.json",
      "response": "instance-ors-enb-schema.json",
      "index": 1
    },
    "enb": {
      "title": "eNB / gNB (obsolete)",
      "software-type": "enb",
      "description": "eNodeB / gNodeB Configuration",
      "request": "instance-ors-enb-gnb-input-schema.json",
      "response": "instance-ors-enb-schema.json",
      "index": 2
    },
    "gnb": {
      "title": "eNB / gNB (obsolete)",
      "software-type": "gnb",
      "description": "eNodeB / gNodeB Configuration",
      "request": "instance-ors-enb-gnb-input-schema.json",
      "response": "instance-ors-enb-schema.json",
      "index": 3
    },
    "ue": {
      "title": "UE",
      "software-type": "ue",
      "description": "User Equipment Configuration",
      "request": "instance-ors-ue-input-schema.json",
      "response": "instance-ors-ue-schema.json",
      "index": 4
    },
    "core-network": {
      "title": "Core Network",
      "software-type": "core-network",
      "description": "Core Network Configuration",
      "request": "instance-core-network-input-schema.json",
      "response": "instance-core-network-schema.json",
      "index": 5
    },
    "core-network-slave": {
      "title": "SIM Card",
      "description": "SIM Card",
      "software-type": "core-network",
      "request": "core-network-shared-input-schema.json",
      "response": "sim/schema.json",
      "shared": true,
      "index": 6
    },
    "test-model": {
      "title": "Test Model",
      "software-type": "test-model",
      "description": "Play 3GPP Test Models, allows to measure power or radio quality",
      "request": "instance-test-model-input-schema.json",
      "response": "instance-test-model-schema.json",
      "index": 7
    }
  }
}

=== SlapOS/slapos/software/ors-amarisoft/software-tdd2600.cfg.json
{
  "name": "ORS Amarisoft",
  "description": "4G and 5G amarisoft stack for ORS",
  "serialisation": "json-in-xml",
  "software-type": {
    "enb": {
      "title": "eNB",
      "software-type": "enb",
      "description": "eNodeB Configuration",
      "request": "instance-tdd2600-enb-input-schema.json",
      "response": "instance-tdd2600-enb-schema.json",
      "index": 0
    },
    "enb-epc": {
      "title": "eNB and EPC",
      "software-type": "enb-epc",
      "description": "eNodeB and EPC Configuration",
      "request": "instance-tdd2600-enb-epc-input-schema.json",
      "response": "instance-tdd2600-enb-epc-schema.json",
      "index": 1
    },
    "gnb": {
      "title": "gNB",
      "software-type": "gnb",
      "description": "gNodeB Configuration",
      "request": "instance-tdd2600-gnb-input-schema.json",
      "response": "instance-tdd2600-gnb-schema.json",
      "index": 2
    },
    "gnb-epc": {
      "title": "gNB and EPC",
      "software-type": "gnb-epc",
      "description": "gNodeB and EPC Configuration",
      "request": "instance-tdd2600-gnb-epc-input-schema.json",
      "response": "instance-tdd2600-gnb-epc-schema.json",
      "index": 3
    },
    "epc": {
      "title": "EPC",
      "software-type": "epc",
      "description": "EPC Configuration",
      "request": "instance-epc-input-schema.json",
      "response": "instance-epc-schema.json",
      "index": 4
    },
    "gnb-epc-slave": {
      "title": "Sim Card",
      "description": "Sim Card Configuration",
      "software-type": "gnb-epc",
      "request": "instance-gnb-epc-slave-input-schema.json",
      "response": "instance-gnb-epc-slave-schema.json",
      "shared": true,
      "index": 5
    },
    "enb-epc-slave": {
      "title": "Sim Card",
      "description": "Sim Card Configuration",
      "software-type": "enb-epc",
      "request": "instance-enb-epc-slave-input-schema.json",
      "response": "instance-enb-epc-slave-schema.json",
      "shared": true,
      "index": 6
    },
    "epc-slave": {
      "title": "Sim Card",
      "description": "Sim Card Configuration",
      "software-type": "epc",
      "request": "instance-epc-slave-input-schema.json",
      "response": "instance-epc-slave-schema.json",
      "shared": true,
      "index": 7
    }
  }
}

=== SlapOS/slapos/software/ors-amarisoft/software-tdd-m2ru.cfg.json
{
  "name": "ORS Amarisoft",
  "description": "4G and 5G amarisoft stack for ORS",
  "serialisation": "json-in-xml",
  "software-type": {

    "ue-lte": {
      "title": "UE-LTE",
      "description": "UE LTE Configuration",
      "software-type": "ue-lte",
      "request": "instance-tdd-m2ru-ue-lte-input-schema.json",
      "response": "instance-tdd-m2ru-ue-lte-schema.json",
      "index": 4
    },
    "ue-nr": {
      "title": "UE-NR",
      "description": "UE NR Configuration",
      "software-type": "ue-nr",
      "request": "instance-tdd-m2ru-ue-nr-input-schema.json",
      "response": "instance-tdd-m2ru-ue-nr-schema.json",
      "index": 5
    },

    "enb": {
      "title": "eNB",
      "software-type": "enb",
      "description": "eNodeB Configuration",
      "request": "instance-tdd-m2ru-enb-input-schema.json",
      "response": "instance-tdd-m2ru-enb-schema.json",
      "index": 0
    },
    "gnb": {
      "title": "gNB",
      "software-type": "gnb",
      "description": "gNodeB Configuration",
      "request": "instance-tdd-m2ru-gnb-input-schema.json",
      "response": "instance-tdd-m2ru-gnb-schema.json",
      "index": 1
    },
    "core-network": {
      "title": "Core Network",
      "software-type": "core-network",
      "description": "Core Network Configuration",
      "request": "instance-core-network-input-schema.json",
      "response": "instance-core-network-schema.json",
      "index": 2
    },
    "core-network-slave": {
      "title": "Core Network Sim Card",
      "description": "Core Network Sim Card Configuration",
      "software-type": "core-network",
      "request": "instance-core-network-slave-input-schema.json",
      "response": "instance-core-network-slave-schema.json",
      "shared": true,
      "index": 3
    }
  }
}
