=== SlapOS/slapos/slapos/test/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Slapos Software Release instantiation descriptor",
  "additionalProperties": false,
  "properties": {
    "name": {
      "description": "A short human-friendly name for the sofware release",
      "type": "string"
    },
    "description": {
      "description": "A short description of the sofware release",
      "type": "string"
    },
    "serialisation": {
      "description": "How the parameters and results are serialised",
      "require": true,
      "enum": ["xml", "json-in-xml"],
      "type": "string"
    },
    "software-type": {
      "description": "Existing software types",
      "require": true,
      "patternProperties": {
        ".*": {
          "description": "Software type declaration",
          "additionalProperties": false,
          "properties": {
            "title": {
              "description": "A human-friendly title of the software type",
              "type": "string"
            },
            "description": {
              "description": "A human-friendly description of the software type",
              "type": "string"
            },
            "serialisation": {
              "description": "How the parameters and results are serialised, if different from global setting",
              "enum": ["xml", "json-in-xml"],
              "type": "string"
            },
            "request": {
              "require": true,
              "description": "URL, relative to Software Release base path, of a json schema for values expected by instance of current software type",
              "type": "string"
            },
            "response": {
              "require": true,
              "description": "URL, relative to Software Release base path, of a json schema for values published by instance of current software type",
              "type": "string"
            },
            "index": {
              "description": "Value to use instead of software type id to sort them (in order to display most relevant software types earlier in a list, for example)",
              "type": "number"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}

=== SlapOS/slapos/software/ors-amarisoft/software-fdd.cfg.json
{
  "name": "ORS Amarisoft",
  "description": "4G and 5G amarisoft stack for ORS",
  "serialisation": "json-in-xml",
  "software-type": {

    "ue-lte": {
      "title": "UE-LTE",
      "description": "UE LTE Configuration",
      "software-type": "ue-lte",
      "request": "instance-fdd-ue-lte-input-schema.json",
      "response": "instance-fdd-ue-lte-schema.json",
      "index": 4
    },
    "ue-nr": {
      "title": "UE-NR",
      "description": "UE NR Configuration",
      "software-type": "ue-nr",
      "request": "instance-fdd-ue-nr-input-schema.json",
      "response": "instance-fdd-ue-nr-schema.json",
      "index": 5
    },

    "enb": {
      "title": "eNB",
      "software-type": "enb",
      "description": "eNodeB Configuration",
      "request": "instance-fdd-enb-input-schema.json",
      "response": "instance-fdd-enb-schema.json",
      "index": 0
    },
    "gnb": {
      "title": "gNB",
      "software-type": "gnb",
      "description": "gNodeB Configuration",
      "request": "instance-fdd-gnb-input-schema.json",
      "response": "instance-fdd-gnb-schema.json",
      "index": 1
    },
    "core-network": {
      "title": "Core Network",
      "software-type": "core-network",
      "description": "Core Network Configuration",
      "request": "instance-core-network-input-schema.json",
      "response": "instance-core-network-schema.json",
      "index": 2
    },
    "core-network-slave": {
      "title": "Core Network Sim Card",
      "description": "Core Network Sim Card Configuration",
      "software-type": "core-network",
      "request": "sim/input-schema.json",
      "response": "sim/schema.json",
      "shared": true,
      "index": 3
    }
  }
}

=== SlapOS/slapos/software/caddy-frontend/software.cfg.json
{
  "description": "Caddy Frontend",
  "name": "Caddy Frontend",
  "serialisation": "xml",
  "software-type": {
    "custom-personal": {
      "description": "",
      "index": 2,
      "request": "instance-caddy-input-schema.json",
      "response": "instance-output-schema.json",
      "title": "Custom Personal"
    },
    "custom-personal-slave": {
      "description": "Custom Personal",
      "index": 1,
      "request": "instance-slave-caddy-input-schema.json",
      "response": "instance-output-schema.json",
      "shared": true,
      "software-type": "custom-personal",
      "title": "Custom Personal (Slave)"
    },
    "default": {
      "description": "Default",
      "index": 3,
      "request": "instance-caddy-input-schema.json",
      "response": "instance-output-schema.json",
      "software-type": "default",
      "title": "Default"
    },
    "default-slave": {
      "description": "Default",
      "index": 4,
      "request": "instance-slave-caddy-input-schema.json",
      "response": "instance-output-schema.json",
      "shared": true,
      "software-type": "default",
      "title": "Default (slave)"
    }
  }
}

=== SlapOS/slapos/software/galene/software-ptt.cfg.json
{
  "name": "Galene",
  "description": "Galene Video-conferencing",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "default",
      "software-type": "default",
      "description": "default",
      "request": "instance-ptt-default-input-schema.json",
      "response": "instance-ptt-default-output-schema.json",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/lte/software.cfg.json
{
    "name": "LTE",
    "description": "LTE",
    "serialisation": "json-in-xml",
    "software-type": {
        "enb": {
             "title": "eNB",
             "software-type": "enb",
             "description": "eNodeB Configuration",
             "request": "instance-enb-input-schema.json",
             "response": "instance-enb-schema.json",
             "index": 0
         },
        "epc": {
             "title": "EPC",
             "software-type": "epc",
             "description": "EPC Configuration",
             "request": "instance-epc-input-schema.json",
             "response": "instance-epc-schema.json",
             "index": 1
         },
        "ims": {
             "title": "IMS",
             "software-type": "ims",
             "description": "IMS Configuration",
             "request": "instance-ims-input-schema.json",
             "response": "instance-ims-schema.json",
             "index": 2
         },
        "default": {
            "title": "Default",
            "software-type": "default",
            "description": "Default",
            "request": "instance-lte-input-schema.json",
            "response": "instance-lte-schema.json",
            "index": 3
        }
    }
}

=== SlapOS/slapos/software/backupserver/software.cfg.json
{
  "name": "Backupserver",
  "description": "Backupserver",
  "serialisation": "xml",
  "software-type": {
    "default": {
      "title": "default",
      "software-type": "default",
      "description": "Default",
      "request": "instance-input-schema.json",
      "response": "instance-output-schema.json",
      "index": 1
    },
    "default-slave": {
      "title": "Default (slave)",
      "description": "Default",
      "index": 4,
      "request": "instance-slave-input-schema.json",
      "response": "instance-slave-output-schema.json",
      "shared": true,
      "software-type": "default"
    }
  }
}

=== SlapOS/slapos/software/wendelin/software.cfg.json
{
  "name": "Wendelin",
  "description": "Wendelin",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "Default",
      "software-type": "default",
      "request": "instance-wendelin-input-schema.json",
      "response": "instance-wendelin-output-schema.json",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/ors-amarisoft/software.cfg.json
{
  "name": "Amarisoft stack",
  "description": "4G and 5G amarisoft stack",
  "serialisation": "json-in-xml",
  "software-type": {
    "enb": {
      "title": "eNB/gNB",
      "software-type": "enb",
      "description": "eNodeB/gNodeB Configuration",
      "request": "instance-enb-input-schema.json",
      "response": "instance-enb-schema.json",
      "index": 1
    },
    "core-network": {
      "title": "Core Network",
      "software-type": "core-network",
      "description": "Core Network Configuration",
      "request": "instance-core-network-input-schema.json",
      "response": "instance-core-network-schema.json",
      "index": 2
    },
    "core-network-slave": {
      "title": "â†’ Core Network | Sim Card",
      "description": "Core Network Sim Card Configuration",
      "software-type": "core-network",
      "request": "sim/input-schema.json",
      "response": "sim/schema.json",
      "shared": true,
      "index": 3
    },
    "ue": {
      "title": "UE",
      "description": "UE Configuration",
      "software-type": "ue",
      "request": "instance-ue-input-schema.json",
      "response": "instance-ue-schema.json",
      "index": 4
    }
  }
}

=== SlapOS/slapos/software/monitor/software.cfg.json
{
  "name": "Monitor",
  "description": "Software release for Monitoring purpose",
  "serialisation": "xml",
  "software-type": {
    "default": {
      "title": "Default",
      "description": "Standalone Monitor",
      "request": "instance-default-input-schema.json",
      "response": "instance-default-output-schema.json",
      "index": 0
    },
    "edgetest-basic": {
      "title": "Edge Test Basic",
      "description": "Basic URL monitoring configuration",
      "request": "instance-edgetest-basic-input-schema.json",
      "response": "instance-edgetest-basic-output-schema.json",
      "serialisation": "json-in-xml",
      "index": 1
    },
    "edgetest": {
      "title": "Edge Test Shared Cluster [OBSOLETE]",
      "description": "Cluster of bots to perform a distributed monitoring with shared instances. OBSOLETE: Overcomplicated, use Edge Test Basic..",
      "request": "instance-edgetest-input-schema.json",
      "response": "instance-default-output-schema.json",
      "serialisation": "json-in-xml",
      "index": 3
    },
    "edgetest-slave": {
      "title": "Edge Test Shared Instance [OBSOLETE]",
      "shared": true,
      "software-type": "edgetest",
      "description": "Definition of monitorig for Edge Test Shared Cluster. OBSOLETE: Overcomplicated, use Edge Test Basic.",
      "request": "instance-edgetest-slave-input-schema.json",
      "response": "instance-default-output-schema.json",
      "serialisation": "json-in-xml",
      "index": 4
    }
  }
}
