=== SlapOS/slapos/slapos/test/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Slapos Software Release instantiation descriptor",
  "additionalProperties": false,
  "properties": {
    "name": {
      "description": "A short human-friendly name for the sofware release",
      "type": "string"
    },
    "description": {
      "description": "A short description of the sofware release",
      "type": "string"
    },
    "serialisation": {
      "description": "How the parameters and results are serialised",
      "require": true,
      "enum": ["xml", "json-in-xml"],
      "type": "string"
    },
    "software-type": {
      "description": "Existing software types",
      "require": true,
      "patternProperties": {
        ".*": {
          "description": "Software type declaration",
          "additionalProperties": false,
          "properties": {
            "title": {
              "description": "A human-friendly title of the software type",
              "type": "string"
            },
            "description": {
              "description": "A human-friendly description of the software type",
              "type": "string"
            },
            "serialisation": {
              "description": "How the parameters and results are serialised, if different from global setting",
              "enum": ["xml", "json-in-xml"],
              "type": "string"
            },
            "request": {
              "require": true,
              "description": "URL, relative to Software Release base path, of a json schema for values expected by instance of current software type",
              "type": "string"
            },
            "response": {
              "require": true,
              "description": "URL, relative to Software Release base path, of a json schema for values published by instance of current software type",
              "type": "string"
            },
            "index": {
              "description": "Value to use instead of software type id to sort them (in order to display most relevant software types earlier in a list, for example)",
              "type": "number"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}

=== SlapOS/slapos/software/notepod/software.cfg.json
{
  "name": "NotePOD",
  "description": "NotePOD is a Ubuntu installer preconfigured for security",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "Default",
      "software-type": "default",
      "description": "Default setup for NotePOD Instance.",
      "request": "instance-notepod.json",
      "response": "",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/ssh/software.cfg.json
{
  "name": "SSH",
  "description": "SSH parameters",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "Default",
      "software-type": "default",
      "description": "Default",
      "request": "instance-ssh-input-schema.json",
      "response": "instance-ssh-output-schema.json",
      "index": 1
    }
  }
}

=== SlapOS/slapos/software/beremiz-runtime/software.cfg.json
{
  "name": "Beremiz-runtime",
  "description": "Beremiz-runtime is a headless implementation of Beremiz-ide which is responsible for compiling and running PLC programs.",
  "serialisation": "xml",
  "software-type": {
    "default": {
      "title": "Default",
      "software-type": "default",
      "description": "Default",
      "request": "instance-input-schema.json",
      "response": "instance-output-schema.json"
    }
  }
}

=== SlapOS/slapos/software/cdn-me/software.cfg.json
{
	"name": "CDN ME",
	"description": "CDN ME",
	"serialisation": "xml",
	"software-type": {
		"default": {
			"title": "Default",
			"description": "Re6st registry",
			"request": "instance-cdn-me-simplified-input-schema.json",
			"response": "instance-cdn-me-output-schema.json",
			"index": 0
		},
		"default-advanced": {
			"title": "Default (Advanced Form)",
                        "software-type": "default",
			"description": "Re6st registry",
			"request": "instance-cdn-me-input-schema.json",
			"response": "instance-cdn-me-output-schema.json",
			"index": 1
		}
	}
}

=== SlapOS/slapos/software/ors-amarisoft/k/tru.cfg.json
{
  "name": "Radio Unit",
  "description": "Radio Unit configuration for Amarisoft/ORS",
  "serialisation": "json-in-xml",
  "software-type": {
    "default": {
      "title": "Defaul",
      "description": "RU configuration",
      "serialisation": "json-in-xml",
      "request":  "../ru/input-schema.json",
      "response": "../ru/input-schema.json",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/headless-chromium/software.cfg.json
{
  "name": "Headless Chromium",
  "description": "Headless (stripped-down) Chromium shell",
  "serialisation": "xml",
  "software-type": {
    "default": {
      "title": "Default",
      "description": "Standalone headless shell",
      "request": "instance-headless-chromium-input-schema.json",
      "response": "instance-headless-chromium-output-schema.json",
      "index": 0
    }
  }
}

=== SlapOS/slapos/software/cdn-requester/software.cfg.json
{
  "name": "CDN Requester",
  "description": "CDN Requester",
  "serialisation": "json-in-xml",
  "software-type": {
    "requester": {
      "title": "CDN Requester",
      "software-type": "requester",
      "request": "instance-requester-input-schema.json",
      "response": "instance-requester-output-schema.json",
      "index": 0
    },
    "cdn-request": {
      "title": "CDN Request",
      "software-type": "requester",
      "request": "instance-slave-input-schema.json",
      "response": "instance-slave-output-schema.json",
      "shared": true,
      "index": 1
    },
    "single-custom-personal": {
      "description": "",
      "index": 2,
      "request": "instance-requester-input-schema.json",
      "response": "instance-requester-output-schema.json",
      "title": "Custom Personal"
    },
    "custom-personal": {
      "description": "",
      "index": 2,
      "request": "instance-requester-input-schema.json",
      "response": "instance-requester-output-schema.json",
      "title": "Custom Personal"
    },
    "custom-personal-slave": {
      "description": "Custom Personal",
      "index": 1,
      "request": "instance-slave-input-schema.json",
      "response": "instance-slave-output-schema.json",
      "shared": true,
      "software-type": "custom-personal",
      "title": "Custom Personal (Slave)"
    },
    "default": {
      "description": "Default",
      "index": 3,
      "request": "instance-requester-input-schema.json",
      "response": "instance-requester-output-schema.json",
      "software-type": "default",
      "title": "Default"
    },
    "default-slave": {
      "description": "Default",
      "index": 4,
      "request": "instance-slave-input-schema.json",
      "response": "instance-slave-output-schema.json",
      "shared": true,
      "software-type": "default",
      "title": "Default (slave)"
    },
    "kedifa": {
      "description": "Kedifa",
      "index": 5,
      "request": "instance-kedifa-input-schema.json",
      "response": "instance-kedifa-output-schema.json",
      "software-type": "kedifa",
      "title": "Kedifa"
    }
  }
}

=== SlapOS/slapos/software/ors-amarisoft/software-ors.cfg.json
{
  "name": "ORS Amarisoft",
  "description": "4G and 5G amarisoft stack for ORS",
  "serialisation": "json-in-xml",
  "software-type": {
    "enb": {
      "title": "eNB",
      "software-type": "enb",
      "description": "eNodeB Configuration",
      "request": "instance-ors-enb-input-schema.json",
      "response": "instance-ors-enb-schema.json",
      "index": 1
    },
    "gnb": {
      "title": "gNB",
      "software-type": "gnb",
      "description": "gNodeB Configuration",
      "request": "instance-ors-gnb-input-schema.json",
      "response": "instance-ors-gnb-schema.json",
      "index": 2
    },
    "ue": {
      "title": "UE",
      "software-type": "ue",
      "description": "User Equipment Configuration",
      "request": "instance-ue-input-schema.json",
      "response": "instance-ue-schema.json",
      "index": 3
    },
    "ue-slave": {
      "title": "UE Sim Card",
      "software-type": "ue",
      "description": "User Equipment Sim Card Configuration",
      "request": "sim/input-schema.json",
      "response": "sim/schema.json",
      "shared": true,
      "index": 4
    },
    "core-network": {
      "title": "Core Network",
      "software-type": "core-network",
      "description": "Core Network Configuration",
      "request": "instance-core-network-input-schema.json",
      "response": "instance-core-network-schema.json",
      "index": 5
    },
    "core-network-slave": {
      "title": "Core Network Sim Card",
      "description": "Core Network Sim Card Configuration",
      "software-type": "core-network",
      "request": "sim/input-schema.json",
      "response": "sim/schema.json",
      "shared": true,
      "index": 6
    }
  }
}
