=== SlapOS/slapos/software/simpleran/instance-ors-enb-gnb-input-schema.json
{
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Input Parameters",
  "properties": {
    "cell1": {
      "title": "Cell Parameters",
      "description": "Radio parameters related to the cell",
      "$ref": "#/$defs/ors_cell"
    },
    "nodeb": {
      "title": "eNB Parameters",
      "description": "Parameters not related to a single cell but to the eNB",
      "allOf": [
        {
          "$ref": "ors-enb-gnb-classic.json"
        },
        {
          "$ref": "ors-enb-gnb.json"
        }
      ],
      "type": "object",
      "default": {}
    },
    "management": {
      "title": "ORS Management Parameters",
      "description": "Parameters which are not related to radio, such as promise thresholds, statistical collection, log verbosity etc...",
      "allOf": [
        {
          "$ref": "ors-params.json"
        }
      ],
      "type": "object",
      "default": {}
    },
    "monitor-interface-url": {
      "title": "Monitor Interface URL",
      "description": "URL to the monitor app used in monitor setup URL",
      "type": "string",
      "default": "https://monitor.app.officejs.com/#page=ojsm_landing"
    },
    "rf-info": {
      "title": "Expert only: RF Info",
      "description": "Expert only: override RF Info from parameters",
      "type": "string",
      "textarea": true
    }
  },
  "$defs": {
    "enable_cell_gnb": {
      "title": "Enable Cell: You must select this parameter to enable the cell",
      "type": "string",
      "enum": [
        "Enable gNB",
        "Disable gNB"
      ],
      "default": "Enable gNB"
    },
    "enable_cell_enb": {
      "$ref": "#/$defs/enable_cell_gnb",
      "enum": [
        "Enable eNB",
        "Disable eNB"
      ],
      "default": "Enable eNB"
    },
    "enable_cell_nb": {
      "$ref": "#/$defs/enable_cell_gnb",
      "enum": [
        "Enable NB IOT",
        "Disable NB IOT"
      ],
      "default": "Enable NB IOT"
    },
    "ors_cell": {
      "oneOf": [
        {
          "title": "gNB Cell",
          "required": [
            "enable_cell"
          ],
          "allOf": [
            {
              "$schema": "https://json-schema.org/draft/2020-12/schema",
              "title": "Cell Type",
              "type": "object",
              "properties": {
                "enable_cell": {
                  "$ref": "#/$defs/enable_cell_gnb"
                }
              }
            },
            {
              "$ref": "ors-cell.json"
            },
            {
              "$ref": "ors-gnb-cell.json"
            },
            {
              "$ref": "ors-cell-secondary.json"
            }
          ],
          "type": "object"
        },
        {
          "title": "eNB Cell",
          "required": [
            "enable_cell"
          ],
          "allOf": [
            {
              "$schema": "https://json-schema.org/draft/2020-12/schema",
              "title": "Cell Type",
              "type": "object",
              "properties": {
                "enable_cell": {
                  "$ref": "#/$defs/enable_cell_enb"
                }
              }
            },
            {
              "$ref": "ors-cell.json"
            },
            {
              "$ref": "ors-enb-cell.json"
            },
            {
              "$ref": "ors-cell-secondary.json"
            }
          ],
          "type": "object"
        },
        {
          "title": "NB IOT Cell",
          "required": [
            "enable_cell",
            "dl_earfcn"
          ],
          "allOf": [
            {
              "$schema": "https://json-schema.org/draft/2020-12/schema",
              "title": "Cell Type",
              "type": "object",
              "properties": {
                "enable_cell": {
                  "$ref": "#/$defs/enable_cell_nb"
                }
              }
            },
            {
              "$ref": "ors-cell.json"
            },
            {
              "$ref": "ors-nb-cell.json"
            },
            {
              "$ref": "ors-cell-secondary.json"
            }
          ],
          "type": "object"
        }
      ],
      "type": "object",
      "default": {}
    }
  }
}

=== SlapOS/slapos/software/simpleran/gnb-params.json
{
    "cell1": {
        "enable_cell": "Enable gNB",
        "tx_power_dbm": 1,
        "tx_gain": 1,
        "rx_gain": 1,
        "cell_id": "1",
        "pci": 1,
        "nr_bandwidth": "20 MHz",
        "nr_band": 1,
        "dl_frequency": 1,
        "tdd_ul_dl_config": "DDDSUUUUUU (5ms,   3DL/6UL), S-slot=2DL:2GP:10UL, high uplink",
        "root_sequence_index": 1,
        "ssb_pos_bitmap": "0010",
        "cipher_algo_pref": [
            "NEA2 (128 bit AES)"
        ],
        "integ_algo_pref": [
            "NIA3 (ZUC)",
            "NIA1 (Snow 3G)"
        ],
        "subcarrier_spacing": 30,
        "trs_presence": true,
        "prach_config_index": 1,
        "amarisoft_ssb_computation": true,
        "ignore_gbr_congestion": true,
        "tx_power_offset": 1
    },
    "nodeb": {
        "n_antenna_dl": 2,
        "n_antenna_ul": 1,
        "gnb_id": "1",
        "gnb_id_bits": 22,
        "amf_list": [
            {
                "name": "1",
                "amf_addr": "1",
                "backup_amf_addr": "2",
                "ngap_bind_addr": "1"
            }
        ],
        "plmn_list_5g": [
            {
                "plmn": "1",
                "tac": "1",
                "ranac": 1,
                "reserved": true
            }
        ],
        "enb_id": "1",
        "mme_list": [
            {
                "name": "1",
                "mme_addr": "1",
                "backup_mme_addr": "1",
                "s1ap_bind_addr": "1"
            }
        ],
        "plmn_list": [
            {
                "plmn": "1",
                "attach_without_pdn": true,
                "reserved": true
            }
        ],
        "gps_sync": true,
        "gtp_addr": "IPv6 Re6st address",
        "x2_peers": [
            {
                "name": "1",
                "x2_addr": "1"
            }
        ],
        "xn_peers": [
            {
                "name": "1",
                "xn_addr": "1"
            }
        ],
        "eutra_eutra_handover": {
            "event": {
                "a3_rsrp": 1
            },
            "hysteresis": 1,
            "time_to_trigger": 1024
        },
        "eutra_nr_handover": {
            "event": {
                "b1_rsrp": 1
            },
            "hysteresis": 1,
            "time_to_trigger": 480
        },
        "nssai": [
            {
                "sst": 1,
                "sd": "5"
            }
        ],
        "nr_nr_handover": {
            "event": {
                "a3_rsrp": 1
            },
            "hysteresis": 1,
            "time_to_trigger": 640
        },
        "nr_eutra_handover": {
            "event": {
                "b1_rsrp": 1
            },
            "hysteresis": 5,
            "time_to_trigger": 640
        },
        "gtp_payload_mtu": 1,
        "mbmsgw_addr": "1",
        "inactivity_timer": 1,
        "handover_a1_rsrp": 1,
        "handover_a1_hysteresis": 1,
        "handover_a1_time_to_trigger": 1024,
        "handover_a2_rsrp": 1,
        "handover_a2_hysteresis": 1,
        "handover_a2_time_to_trigger": 512,
        "handover_meas_gap_config": "Gap Pattern 0"
    },
    "management": {
        "log_phy_debug": false,
        "enb_stats_fetch_period": 1,
        "enb_drb_stats_enabled": true,
        "max_rx_sample_db": 1,
        "min_rxtx_delay": 1,
        "xlog_enabled": false,
        "xlog_forwarding_enabled": true,
        "check_core_network": true,
        "wendelin_telecom_software_release_url": "1",
        "xlog_fluentbit_forward_host": "1",
        "xlog_fluentbit_forward_port": 1,
        "xlog_fluentbit_forward_shared_key": "1",
        "amarisoft_version": "1",
        "websocket_url_ipv6": false,
        "lock": "1"
    },
    "monitor-interface-url": "1",
    "rf-info": "1"
}
